In [7]:
from dputils.scrape import Scraper ,Tag

In [8]:

query = 'phone'
page= 1
webpage= Scraper(f'https://www.amazon.in/s?k={query}&page={page}')
print(webpage.soup.title)

<title>Amazon.in : phone</title>

In [16]:
target= Tag('div',cls='s-main-slot s-result-list s-search-results sg-row')
items = Tag('div',cls='s-result-item') #repeating products
title= Tag('h2',cls='a-size-mini a-spacing-none a-color-base s-line-clamp-2')
price = Tag('span',cls='a-price-whole') #to display the price
rating =Tag('i',cls='a-icon a-icon-star-small a-star-small-4 aok-align-bottom')

In [17]:
webpage.get_all(target, items,title=title, price=price, rating=rating)

[{'title': None, 'price': None, 'rating': None},
 {'title': None, 'price': None, 'rating': None},
 {'title': 'Apple iPhone 13 Mini (128GB) - Midnight  ',
  'price': '64,900',
  'rating': None},
 {'title': 'Apple iPhone 13 (128GB) - Blue  ',
  'price': '61,999',
  'rating': None},
 {'title': 'Nokia 105 Single SIM, Keypad Mobile Phone with Wireless FM Radio | Charcoal  ',
  'price': '1,299',
  'rating': '3.8 out of 5 stars'},
 {'title': 'Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB RAM (2GB RAM + 2GB Virtual RAM) + 64GB Capacity | Light Mint  ',
  'price': '5,999',
  'rating': None},
 {'title': 'OPPO A74 5G (Fantastic Purple,6GB RAM,128GB Storage) with No Cost EMI/Additional Exchange Offers  ',
  'price': '15,740',
  'rating': '4.2 out of 5 stars'},
 {'title': 'Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM, 128GB Storage)  ',
  'price': '34,999',
  'rating': '4.2 out of 5 stars'},
 {'title': None, 'price': None, 'rating': None},
 {'title': 'Samsung Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 | 5000 mAh Battery  ',
  'price': '7,499',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi A1 (Light Green, 2GB RAM 32GB ROM) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Android 12  ',
  'price': '5,899',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi A1 (Black, 2GB RAM, 32GB Storage) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Android 12  ',
  'price': '5,899',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi 10A (Charcoal Black, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | Upto 5GB RAM with RAM Booster  ',
  'price': '8,799',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi Note 12 5G Mystique Blue 6GB RAM 128GB ROM | 1st Phone with 120Hz Super AMOLED and SnapdragonÂ® 4 Gen 1 | 48MP AI Triple Camera  ',
  'price': '19,999',
  'rating': '3.9 out of 5 stars'},
 {'title': 'Apple iPhone 14 Pro (1 TB) - Gold  ',
  'price': '1,73,139',
  'rating': None},
 {'title': 'Apple iPhone 14 Pro Max (1 TB) - Gold  ',
  'price': '1,89,900',
  'rating': None},
 {'title': 'Redmi 11 Prime 5G (Chrome Silver, 4GB RAM 64GB ROM) | Prime Design | MTK Dimensity 700 | 50 MP Dual Cam | 5000mAh | 7 Band 5G  ',
  'price': '13,499',
  'rating': '3.9 out of 5 stars'},
 {'title': None, 'price': None, 'rating': None},
 {'title': 'Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery  ',
  'price': '6,499',
  'rating': '4.1 out of 5 stars'},
 {'title': 'Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB RAM (2GB RAM + 2GB Virtual RAM) + 64GB Capacity | Charcoal  ',
  'price': '5,999',
  'rating': None},
 {'title': 'Oppo A78 5G (Glowing Black, 8GB RAM, 128 Storage) | 5000 mAh Battery with 33W SUPERVOOC Charger| 50MP AI Camera | 90Hz Refresh Rate | with No Cost EMI/Additional Exchange Offers  ',
  'price': '18,999',
  'rating': '4.2 out of 5 stars'},
 {'title': 'Nokia 2660 Flip 4G Volte keypad Phone with Dual SIM, Dual Screen, inbuilt MP3 Player & Wireless FM Radio | Blue  ',
  'price': '4,499',
  'rating': None},
 {'title': 'Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 | 5000 mAh Battery  ',
  'price': '7,499',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Nokia 2660 Flip 4G Volte keypad Phone with Dual SIM, Dual Screen, inbuilt MP3 Player & Wireless FM Radio | Black  ',
  'price': '4,499',
  'rating': None},
 {'title': 'OPPO A15s (Fancy White, 4GB, 128GB Storage) AI Triple Camera | 6.52" HD+ Screen | 2.3GHz Mediatek Helio P35 Octa Core Processor  ',
  'price': '11,490',
  'rating': '4.2 out of 5 stars'},
 {'title': 'Apple iPhone SE (64 GB) - Midnight (3rd Generation)  ',
  'price': '49,900',
  'rating': None},
 {'title': 'Apple iPhone 14 Plus (256 GB) - Blue  ',
  'price': '94,900',
  'rating': None},
 {'title': 'Redmi 9 Activ (Carbon Black, 4GB RAM, 64GB Storage) | Octa-core Helio G35 | 5000 mAh Battery  ',
  'price': '548.',
  'rating': '4.1 out of 5 stars'},
 {'title': 'Redmi 9 Activ (Carbon Black, 4GB RAM, 64GB Storage) | Octa-core Helio G35 | 5000 mAh Battery  ',
  'price': None,
  'rating': '4.1 out of 5 stars'},
 {'title': 'IPHONE UNLOCKED  ', 'price': '548.', 'rating': None},
 {'title': "Nillkin A53 5G Case, for Samsung Galaxy A53 5G Case, CamShield Pro Case with Slide Camera Cover, for Samsung a53 5g A Series Smartphone case 6.46'' -2022 (Black)  ",
  'price': '1,075',
  'rating': None},
 {'title': 'Samsung Galaxy S21 FE 5G (Graphite, 8GB, 128GB Storage)  ',
  'price': '35,601',
  'rating': '4.1 out of 5 stars'},
 {'title': 'Redmi A1 (Light Blue, 2GB RAM, 32GB Storage) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Android 12  ',
  'price': '5,899',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery  ',
  'price': '6,499',
  'rating': '4.1 out of 5 stars'},
 {'title': 'Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 | 5000 mAh Battery  ',
  'price': '7,499',
  'rating': '4.0 out of 5 stars'},
 {'title': 'Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | Upto 5GB RAM with RAM Booster  ',
  'price': '8,799',
  'rating': '4.0 out of 5 stars'},
 {'title': None, 'price': None, 'rating': None},
 {'title': None, 'price': None, 'rating': None},
 {'title': None, 'price': None, 'rating': None}]

In [9]:
def scrape_product(query,page=1):
    webpage= Scraper(f'https://www.amazon.in/s?k={query}&page={page}')
    print(webpage.soup.title)
    #important
    target= Tag('div',cls='s-main-slot s-result-list s-search-results sg-row')
    items = Tag('div',cls='s-result-item') #repeating products
    title= Tag('h2',cls='a-size-mini a-spacing-none a-color-base     s-line-clamp-2')
    price = Tag('span',cls='a-price-whole') #to display the price
    rating =Tag('i',cls='a-icon a-icon-star-small a-star-small-4     aok-align-bottom')
    return webpage.get_all(target, items,title=title, price=price, rating=rating)

In [10]:
all_data = []
query='laptops'
for i in range(1,15):
    all_data.extend(scrape_product(query, i))
    print(f'Page {i} done')

<title>Amazon.in : laptops</title>
Page 1 done
<title>Amazon.in : laptops</title>
Page 2 done
<title>Amazon.in : laptops</title>
Page 3 done
<title>Amazon.in : laptops</title>
Page 4 done
<title>Amazon.in : laptops</title>
Page 5 done
<title>Amazon.in : laptops</title>
Page 6 done
<title>Amazon.in : laptops</title>
Page 7 done
<title>Amazon.in : laptops</title>
Page 8 done
<title>Amazon.in : laptops</title>
Page 9 done
<title>Amazon.in : laptops</title>
Page 10 done
<title>Amazon.in : laptops</title>
Page 11 done
<title>Amazon.in : laptops</title>
Page 12 done
<title>Amazon.in : laptops</title>
Page 13 done
<title>Amazon.in : laptops</title>
Page 14 done

In [11]:
import pandas as pd
df = pd.DataFrame(all_data).dropna(how='all')
df.to_csv('laptops.csv',index=False)

In [12]:
df

    title   price rating
2    None  39,990   None
3    None  41,990   None
4    None  44,490   None
5    None  26,999   None
6    None  33,639   None
..    ...     ...    ...
444  None  39,990   None
445  None  25,490   None
446  None  17,263   None
447  None  64,999   None
448  None  56,990   None

[340 rows x 3 columns]